id: IAC848AEC
legacy_id: P000529
ocr_import_info:
  bdrc_scan_id: W1KG15383
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:09:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:18:30.988490+00:00'
last_modified: 2022-08-31 16:19:28.666772
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15383
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15383
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཁྲིད་ཆེན་བརྒྱད་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9417161494581078
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15396:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15396
      total_pages: 360
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15396.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9348414646775174
    legacy_id: v002
  I1KG15395:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15395
      total_pages: 852
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15395.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9416087302218226
    legacy_id: v001
  I1KG15397:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15397
      total_pages: 464
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15397.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9472088271015154
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
